server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-controle-usuario
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-controle-usuarios
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
