server:
  port: 8080
spring:
  application:
    name: ms-controle-usuario
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/controle
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8030
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



