server:
  port: 8000
spring:
  application:
    name: ms-controle-usuario
  datasource:
    url: jdbc:postgresql://localhost:5432/controle
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwksUri: http://localhost:8200/oauth2/jwks

